project_id = "brqzedcxzjqwzpkwrmow"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.cancel-order-refund]
    verify_jwt = false
  [functions.cart-reminder]
    verify_jwt = false
  [functions.create-subaccount]
    verify_jwt = false
  [functions.get-recommendations]
    verify_jwt = false
  [functions.initialize-delivery-subscription]
    verify_jwt = false
  [functions.initialize-payment]
    verify_jwt = false
  [functions.initialize-subscription]
    verify_jwt = false
  [functions.lite]
    verify_jwt = false
  [functions.notify-new-device]
    verify_jwt = true
  [functions.og-redirect]
    verify_jwt = false
  [functions.payout-delivery]
    verify_jwt = false
  [functions.paystack-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.reconcile-payments]
    verify_jwt = false
  [functions.reconcile-wallet]
    verify_jwt = false
  [functions.request-withdrawal]
    verify_jwt = false
  [functions.send-email-notification]
    verify_jwt = false
  [functions.send-push-notification]
    verify_jwt = false
  [functions.verify-payment]
    verify_jwt = false
