project_id = "brqzedcxzjqwzpkwrmow"

[functions.send-push-notification]
verify_jwt = false

[functions.get-recommendations]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = false

[functions.og-redirect]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.payout-delivery]
verify_jwt = false

[functions.create-subaccount]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = false

[functions.cancel-order-refund]
verify_jwt = false

[functions.initialize-subscription]
verify_jwt = false

[functions.cart-reminder]
verify_jwt = false

[functions.notify-new-device]
verify_jwt = true
