/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: Array<{ url: string; revision: string | null }> };

// Take control immediately so updates apply ASAP
self.skipWaiting();
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// ============================================
// NAVIGATION: NetworkFirst so updates show up
// ============================================
// HTML navigations always try the network first. Falls back to the precached
// index.html only when offline. Excludes OAuth and password reset routes.
const navigationHandler = new NetworkFirst({
  cacheName: 'navigations',
  networkTimeoutSeconds: 5,
  plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 })],
});

registerRoute(
  new NavigationRoute(navigationHandler, {
    denylist: [/^\/~oauth/, /^\/reset-password/, /^\/api\//, /^\/auth\/v1\//],
  })
);

// Hashed static assets: CacheFirst is fine because filenames change each build
registerRoute(
  ({ request, url }) =>
    url.origin === self.location.origin &&
    (request.destination === 'script' || request.destination === 'style' || request.destination === 'font'),
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  })
);

// Images (product/store images from same-origin or Supabase Storage) — CacheFirst
registerRoute(
  ({ request, url }) =>
    request.destination === 'image' &&
    (url.origin === self.location.origin || /supabase\.co$/.test(url.hostname)),
  new CacheFirst({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30, purgeOnQuotaError: true })],
  })
);

// Supabase REST GETs — NetworkFirst so cached catalog data serves offline
registerRoute(
  ({ request, url }) =>
    request.method === 'GET' &&
    /supabase\.co$/.test(url.hostname) &&
    url.pathname.startsWith('/rest/v1/'),
  new NetworkFirst({
    cacheName: 'supabase-reads',
    networkTimeoutSeconds: 5,
    plugins: [new ExpirationPlugin({ maxEntries: 80, maxAgeSeconds: 60 * 60 * 24 })],
  })
);

// ============================================
// PUSH NOTIFICATION HANDLERS
// ============================================

self.addEventListener('push', (event: PushEvent) => {
  console.log('[SW] Push event received:', event);

  if (!event.data) {
    console.log('[SW] No data in push event');
    return;
  }

  try {
    const data = event.data.json();
    console.log('[SW] Push notification data:', data);

    const options = {
      body: data.body || 'You have a new notification',
      icon: data.icon || '/icons/icon-192x192.png',
      badge: data.badge || '/icons/icon-72x72.png',
      tag: data.tag || 'default',
      data: data.data || {},
      vibrate: [100, 50, 100],
      requireInteraction: true,
    } as NotificationOptions;

    event.waitUntil(
      self.registration.showNotification(data.title || 'Jayee Express', options)
    );
  } catch (error) {
    console.error('[SW] Error handling push event:', error);
  }
});

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[SW] Notification clicked:', event);

  event.notification.close();

  const data = event.notification.data || {};
  let targetUrl = '/';

  if (data.type === 'message') {
    targetUrl = '/messages';
  } else if (data.type === 'order' && data.url) {
    targetUrl = data.url;
  } else if (data.type === 'order') {
    targetUrl = '/seller';
  } else if (data.url) {
    targetUrl = data.url;
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          client.focus();
          if ('navigate' in client) {
            return (client as WindowClient).navigate(targetUrl);
          }
          return client;
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});

self.addEventListener('pushsubscriptionchange', (event) => {
  console.log('[SW] Push subscription changed:', event);
});

console.log('[SW] Service worker loaded with auto-update + push support');
