// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function publicClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search active products on Jayee Express by keyword, category, or city. Returns id, name, price (GHS), category, store, and city.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text to match against product name/description."),
    category: z.string().trim().optional().describe("Filter by product category."),
    city: z.string().trim().optional().describe("Filter by city (e.g. Accra, Tamale, Wa)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, city, limit }) => {
    const supabase = publicClient();
    let q = supabase.from("products").select(
      "id, name, description, price, category, image_url, store:stores!inner(id, name, slug, city, is_verified, is_suspended, subscription_expires_at)"
    ).eq("is_active", true).eq("store.is_verified", true).eq("store.is_suspended", false).gt("store.subscription_expires_at", (/* @__PURE__ */ new Date()).toISOString()).limit(limit ?? 20);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    if (city) q = q.eq("store.city", city);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function publicClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single Jayee Express product by its id, including store info.",
  inputSchema: {
    id: z2.string().uuid().describe("Product UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = publicClient2();
    const { data, error } = await supabase.from("products").select(
      "id, name, description, price, category, image_url, images, stock, is_service, views, store:stores(id, name, slug, city, is_verified, is_suspended)"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-stores.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function publicClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_stores_default = defineTool3({
  name: "list_stores",
  title: "List stores",
  description: "List verified, active stores on Jayee Express, optionally filtered by city (e.g. Tamale, Wa).",
  inputSchema: {
    city: z3.string().trim().optional().describe("Filter by city."),
    query: z3.string().trim().optional().describe("Match store name."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, query, limit }) => {
    const supabase = publicClient3();
    let q = supabase.from("stores").select("id, name, slug, description, city, category, logo_url, is_verified, subscription_expires_at").eq("is_verified", true).eq("is_suspended", false).gt("subscription_expires_at", (/* @__PURE__ */ new Date()).toISOString()).limit(limit ?? 20);
    if (city) q = q.eq("city", city);
    if (query) q = q.ilike("name", `%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { stores: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "brqzedcxzjqwzpkwrmow";
var mcp_default = defineMcp({
  name: "jayee-express-mcp",
  title: "Jayee Express",
  version: "0.1.0",
  instructions: "Read-only tools for the Jayee Express community marketplace (Accra, Tamale & Wa, Ghana). Use search_products to find items by keyword/category/city, get_product for a single product's details, and list_stores to browse verified stores. Prices are in Ghana Cedis (GHS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_stores_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
